#create Character
#find Character
#find characters that start w any letter, create objects & return array
#return find all characters in a given movie Title

class Character
end

class Movie
end



CHARACTERS = {
  "Abby Mallard": { "Voice":"Joan Cusac [1", "Movie Title":"Chicken Little"},
  "Abigail Gabble": { "Voice":"Monica Evan [2", "Movie Title":"The Aristocats"},
  "Abis Mal": { "Voice":"Jason Alexande [3", "Movie Title":"The Return of Jafar"},
  "Abu": { "Voice":"Frank Welke [4", "Movie Title":"Aladdin"},
  "Achilles": { "Voice":"Non [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Adella": { "Voice":"Sherry Lyn [6", "Movie Title":"The Little Mermaid"},
  "Adorabeezle Winterpop": { "Voice":"None", "Movie Title":"Wreck-It Ralph"},
  "The Agent": { "Voice":"Greg German [7", "Movie Title":"Bolt"},
  "Agent Wendy Pleakley": { "Voice":"Kevin McDonal [8", "Movie Title":"Lilo & Stitch"},
  "Ajax the Gorilla": { "Voice":"None", "Movie Title":"Donald Duck and the Gorilla"},
  "Akela": { "Voice":"John Abbot [9", "Movie Title":"The Jungle Book"},
  "Al the Alligator": { "Voice":"Thurl Ravenscrof [10", "Movie Title":"Lady and the Tramp"},
  "Aladar": { "Voice":"D. B. Sweene [11", "Movie Title":"Dinosaur"},
  "Aladdin": { "Voice":"Scott Weinger\nBrad Kan [4", "Movie Title":"Aladdin"},
  "Alameda Slim": { "Voice":"Randy Quai [12", "Movie Title":"Home on the Range"},
  "Alan-a-Dale": { "Voice":"Roger Mille [13", "Movie Title":"Robin Hood"},
  "Alana": { "Voice":"Kimmy Robertso [6", "Movie Title":"The Little Mermaid"},
  "Alcmene": { "Voice":"Barbara Barri [14", "Movie Title":"Hercules"},
  "Alice": { "Voice":"Kathryn Beaumon [15", "Movie Title":"Alice in Wonderland"},
  "Alice Bluebonnet": { "Voice":"None", "Movie Title":"Make Mine Music"},
  "Alices Sister": { "Voice":"Heather Ange [15", "Movie Title":"Alice in Wonderland"},
  "Amelia Gabble": { "Voice":"Carole Shelle [2", "Movie Title":"The Aristocats"},
  "Amos Slade": { "Voice":"Jack Albertso [16", "Movie Title":"The Fox and the Hound"},
  "Amphitryon": { "Voice":"Hal Holbroo [14", "Movie Title":"Hercules"},
  "Anastasia Tremaine": { "Voice":"Lucille Blis [17", "Movie Title":"Cinderella"},
  "Anda": { "Voice":"Andrea Marti [18", "Movie Title":"Brother Bear 2"},
  "Andrina": { "Voice":"Tara Strong", "Movie Title":"The Little Mermaid"},
  "Angel": { "Voice":"Alyssa Milan [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Angelique": { "Voice":"Bernadette Peters", "Movie Title":"Beauty and the Beast: The Enchanted Christmas"},
  "Angus MacBadger": { "Voice":"Campbell Gran [20", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Anita Radcliffe": { "Voice":"Lisa Davi [21", "Movie Title":"101 Dalmatians"},
  "Anna": { "Voice":"Kristen Bell", "Movie Title":"Frozen"},
  "Annette": { "Voice":"Debi Derryberr [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Apollo": { "Voice":"Keith Davi [14", "Movie Title":"Hercules"},
  "April": { "Voice":"None", "Movie Title":"House of Mouse"},
  "Aquata": { "Voice":"Grey DeLisle\nMona Marshall", "Movie Title":"The Little Mermaid"},
  "Aracuan Bird": { "Voice":"Pinto Colvi [22", "Movie Title":"The Three Caballeros"},
  "The Archdeacon": { "Voice":"David Ogden Stier [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Archimedes": { "Voice":"Junius Matthew [24", "Movie Title":"The Sword in the Stone"},
  "Archimedes Q. Porter": { "Voice":"Nigel Hawthorn [23", "Movie Title":"Tarzan"},
  "Ariel": { "Voice":"Jodi Benson", "Movie Title":"The Little Mermaid"},
  "Arista": { "Voice":"Kimmy Robertson", "Movie Title":"The Little Mermaid"},
  "Armoire": { "Voice":"Jo Anne Worle [25", "Movie Title":"Beauty and the Beast"},
  "Arthur": { "Voice":"David Lander", "Movie Title":"Jungle Cubs"},
  "Arthur/Wart": { "Voice":"Rickie Sorense [24", "Movie Title":"The Sword in the Stone"},
  "Arthur/Wart": { "Voice":"Richard Reitherma [24", "Movie Title":"The Sword in the Stone"},
  "Arthur/Wart": { "Voice":"Robert Reitherma [24", "Movie Title":"The Sword in the Stone"},
  "Assistant Mayor Dawn Bellwether": { "Voice":"Jenny Slate", "Movie Title":"Zootopia"},
  "Atka": { "Voice":"Jeff Bennet [18", "Movie Title":"Brother Bear 2"},
  "Atropos": { "Voice":"Paddi Edward [14", "Movie Title":"Hercules"},
  "Attina": { "Voice":"Kari Wahlgren", "Movie Title":"The Little Mermaid"},
  "Audrey Ramirez": { "Voice":"Jacqueline Obrador [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Audrey the Chicken": { "Voice":"Estelle Harri [12", "Movie Title":"Home on the Range"},
  "Aunt Sarah": { "Voice":"Verna Felto [27", "Movie Title":"Lady and the Tramp"},
  "Aunt Siqiniq": { "Voice":"Wendie Malic [18", "Movie Title":"Brother Bear 2"},
  "Aunt Taqqiq": { "Voice":"Kathy Najim [18", "Movie Title":"Brother Bear 2"},
  "Aurora": { "Voice":"Mary Cost [28", "Movie Title":"Sleeping Beauty"},
  "Axe": { "Voice":"Jeff Bennett", "Movie Title":"Beauty and the Beast: The Enchanted Christmas"},
  "B.E.N.": { "Voice":"Martin Short", "Movie Title":"Treasure Plane [29"},
  "Babette": { "Voice":"Mary Kay Bergma [25", "Movie Title":"Beauty and the Beast"},
  "Babyface Beagle": { "Voice":"Terry McGovern", "Movie Title":"DuckTales"},
  "Baby Red Bird": { "Voice":"Tress MacNeille", "Movie Title":"Mickey Mouse Clubhouse"},
  "Baby Herman": { "Voice":"April Winchel [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Lou Hirsc [30": { "Voice":"", "Movie Title":""},
  "Backwoods Beagle": { "Voice":"Danny Man [31", "Movie Title":"DuckTales"},
  "Bacon Beagle": { "Voice":"None", "Movie Title":"DuckTales"},
  "Baggy Beagle": { "Voice":"Frank Welker", "Movie Title":"DuckTales"},
  "Bagheera": { "Voice":"Sebastian Cabo [9", "Movie Title":"The Jungle Book"},
  "Baileywick": { "Voice":"Tim Gunn", "Movie Title":"Sofia the First"},
  "Baker": { "Voice":"Alex Murphe [25", "Movie Title":"Beauty and the Beast"},
  "Baker": { "Voice":"Rob Paulsen", "Movie Title":"Cinderella II: Dreams Come True"},
  "Ballerina": { "Voice":"None", "Movie Title":"Fantasia 2000"},
  "Baloo Bear": { "Voice":"Phil Harri [9", "Movie Title":"The Jungle Book"},
  "Bambi": { "Voice":"Donnie Dunaga [32", "Movie Title":"Bambi"},
  "Hardie Albrigh [32": { "Voice":"", "Movie Title":""},
  "Alexander Gould": { "Voice":"", "Movie Title":""},
  "Bambis Mother": { "Voice":"Paula Winslow [32 \nCarolyn Hennesy", "Movie Title":"Bambi"},
  "Banzai": { "Voice":"Cheech Mari [33", "Movie Title":"The Lion King"},
  "Bankjob Beagle": { "Voice":"Peter Cullen", "Movie Title":"DuckTales"},
  "Bartholomew": { "Voice":"Barrie Ingha [34", "Movie Title":"The Great Mouse Detective"},
  "Bashful": { "Voice":"Scotty Mattra [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Basil of Baker Street": { "Voice":"Barrie Ingha [34", "Movie Title":"The Great Mouse Detective"},
  "Baylene": { "Voice":"Joan Plowrigh [11", "Movie Title":"Dinosaur"},
  "Bear": { "Voice":"Dal McKennon", "Movie Title":"Bedknobs and Broomsticks"},
  "Beary Barrington": { "Voice":"Haley Joel Osment", "Movie Title":"The Country Bears"},
  "Beast": { "Voice":"Robby Benso [25", "Movie Title":"Beauty and the Beast"},
  "Beaver": { "Voice":"Stan Freber [27", "Movie Title":"Lady and the Tramp"},
  "Bella": { "Voice":"Frank Welker", "Movie Title":"Mickey Mouse Clubhouse"},
  "Belle": { "Voice":"Paige OHar [25", "Movie Title":"Beauty and the Beast"},
  "Ben": { "Voice":"Billy Connoll [36", "Movie Title":"Pocahontas"},
  "Ben Ali Gator": { "Voice":"Jim Cummings", "Movie Title":"Fantasia"},
  "Benjamin Clawhauser": { "Voice":"Nate Torrence", "Movie Title":"Zootopia"},
  "Benny the Cab": { "Voice":"Charles Fleische [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Bent-Tail the Coyote": { "Voice":"Unknown", "Movie Title":"The Legend of Coyote Rock"},
  "Bent-Tail Junior": { "Voice":"Unknown", "Movie Title":"Sheep Dog"},
  "Bentina Beakley": { "Voice":"Joan Gerber", "Movie Title":"DuckTales"},
  "Beret Girl": { "Voice":"Vicki Lewis", "Movie Title":"An Extremely Goofy Movie"},
  "Berlioz": { "Voice":"Dean Clar [2", "Movie Title":"The Aristocats"},
  "Bernard": { "Voice":"Bob Newhar [37", "Movie Title":"The Rescuers"},
  "Big Al": { "Voice":"James Gammon", "Movie Title":"The Country Bears"},
  "Big Bad Wolf": { "Voice":"Billy Bletcher", "Movie Title":"Three Little Pigs"},
  "Big Mama": { "Voice":"Pearl Baile [16", "Movie Title":"The Fox and the Hound"},
  "Bigtime Beagle": { "Voice":"Frank Welker", "Movie Title":"DuckTales"},
  "Bill the Lizard": { "Voice":"Larry Gre [15", "Movie Title":"Alice in Wonderland"},
  "Billy Boss": { "Voice":"Thurl Ravenscrof [2", "Movie Title":"The Aristocats"},
  "Billy Bones": { "Voice":"Patrick McGooha [29", "Movie Title":"Treasure Planet"},
  "Bimbette": { "Voice":"Kath Souci [25", "Movie Title":"Beauty and the Beast"},
  "Binkie Muddlefoot": { "Voice":"Susan Tolsky", "Movie Title":"Darkwing Duck"},
  "Binky Beagle": { "Voice":"None", "Movie Title":"DuckTales"},
  "Black Bart": { "Voice":"Thurl Ravenscrof [24", "Movie Title":"The Sword in the Stone"},
  "Blake": { "Voice":"Nick Swardso [7", "Movie Title":"Bolt"},
  "Blaze": { "Voice":"None", "Movie Title":"Tinker Bell and the Lost Treasure"},
  "Blue Fairy": { "Voice":"Evelyn Venabl [38", "Movie Title":"Pinocchio"},
  "Bobble": { "Voice":"Rob Paulsen", "Movie Title":"Disney Fairies"},
  "Bolt": { "Voice":"John Travolt [7", "Movie Title":"Bolt"},
  "Bomber Beagle": { "Voice":"Robert Ridgel [31", "Movie Title":"DuckTales"},
  "Bonnie Hopps": { "Voice":"Bonnie Hunt", "Movie Title":"Zootopia"},
  "Bookseller": { "Voice":"Alvin Epstei [25", "Movie Title":"Beauty and the Beast"},
  "Boomer": { "Voice":"Paul Winchel [16", "Movie Title":"The Fox and the Hound"},
  "Bonkers D. Bobcat": { "Voice":"Jim Cummings", "Movie Title":"Bonkers"},
  "Boss Beaver": { "Voice":"Brad Garrett", "Movie Title":"Timon and Pumbaa"},
  "Bouncer Beagle": { "Voice":"Chuck McCann", "Movie Title":"DuckTales"},
  "Bowler Hat Guy": { "Voice":"Stephen J. Anderso [39", "Movie Title":"Meet the Robinsons"},
  "Brer Bear": { "Voice":"Nick Stewar [40", "Movie Title":"Song of the South"},
  "Brer Fox": { "Voice":"James Basket [40", "Movie Title":"Song of the South"},
  "Brer Rabbit": { "Voice":"Johnny Le [40", "Movie Title":"Song of the South"},
  "Bradley Uppercrust III": { "Voice":"Jeff Bennett", "Movie Title":"An Extremely Goofy Movie"},
  "Bruno the Dog": { "Voice":"Jimmy MacDonal [17 \nFrank Welker", "Movie Title":"Cinderella"},
  "Bruton": { "Voice":"Peter Siragus [11", "Movie Title":"Dinosaur"},
  "Brutus and Nero": { "Voice":"Candy Candido", "Movie Title":"The Rescuers"},
  "Buck": { "Voice":"Cuba Gooding Jr [12", "Movie Title":"Home on the Range"},
  "Buck Cluck": { "Voice":"Garry Marshal [1", "Movie Title":"Chicken Little"},
  "Bucky Bug": { "Voice":"None", "Movie Title":"Silly Symphonies"},
  "Bucky Oryx-Antlerson": { "Voice":"Byron Howard", "Movie Title":"Zootopia"},
  "Bucky the Squirrel": { "Voice":"Bob Berge [41", "Movie Title":"The Emperors New Groove"},
  "Buford the Cook": { "Voice":"Michael Colya [42", "Movie Title":"The Princess and the Frog"},
  "Bugle Beagle": { "Voice":"Brian Cummings", "Movie Title":"DuckTales"},
  "Burger Beagle": { "Voice":"Chuck McCann", "Movie Title":"DuckTales"},
  "Buster": { "Voice":"Chazz Palminter [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Butch the Bulldog": { "Voice":"Frank Welker", "Movie Title":"Bone Trouble"},
  "Buzzie the Vulture": { "Voice":"J. Pat OMalle [9", "Movie Title":"The Jungle Book"},
  "Cadpig": { "Voice":"Kath Soucie", "Movie Title":"101 Dalmatians: The Series"},
  "Calliope": { "Voice":"Lillias Whit [14", "Movie Title":"Hercules"},
  "Candlehead": { "Voice":"Katie Lowes", "Movie Title":"Wreck-It Ralph"},
  "The Captain": { "Voice":"Thurl Ravenscrof [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Captain Amelia": { "Voice":"Emma Thompso [29", "Movie Title":"Treasure Planet"},
  "Captain Hook": { "Voice":"Hans Conrie [43", "Movie Title":"Peter Pan"},
  "Captain John Smith": { "Voice":"Mel Gibso [36", "Movie Title":"Pocahontas"},
  "Captain Phoebus": { "Voice":"Kevin Klin [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Carl the Robot": { "Voice":"Harland William [39", "Movie Title":"Meet the Robinsons"},
  "Carlotta the Maid": { "Voice":"Edie McClur [6", "Movie Title":"The Little Mermaid"},
  "The Carpenter": { "Voice":"J. Pat OMalle [15", "Movie Title":"Alice in Wonderland"},
  "Casey Junior": { "Voice":"Margaret Wrigh [44", "Movie Title":"Dumbo"},
  "Cash": { "Voice":"Patrick Swayze", "Movie Title":"The Fox and the Hound 2"},
  "Cassim": { "Voice":"John Rhys-Davie [45", "Movie Title":"Aladdin and the King of Thieves"},
  "The Caterpillar": { "Voice":"Richard Hayd [15", "Movie Title":"Alice in Wonderland"},
  "Catty the Elephant": { "Voice":"Noreen Gammil [44", "Movie Title":"Dumbo"},
  "Cecil the Vulture": { "Voice":"Michael McKean", "Movie Title":"Jungle Cubs"},
  "Cedric the Sorcerer": { "Voice":"Jess Harnell", "Movie Title":"Sofia the First"},
  "Chaca": { "Voice":"Kellyann Kels [41", "Movie Title":"The Emperors New Groove"},
  "Chandeleria": { "Voice":"April Winchell", "Movie Title":"Belles Magical World"},
  "Chair Mouse": { "Voice":"Bernard Fo [37", "Movie Title":"The Rescuers"},
  "Chainsaw": { "Voice":"Frank Welker", "Movie Title":"Goof Troop"},
  "Charlotte La Bouff": { "Voice":"Jennifer Cod [42", "Movie Title":"The Princess and the Frog"},
  "Cheetata and Cheetato": { "Voice":"Rob Paulsen\nJim Cummings", "Movie Title":"Timon and Pumbaa"},
  "Chef Bouche": { "Voice":"Brian Cumming [25", "Movie Title":"Beauty and the Beast"},
  "Chef Louis": { "Voice":"René Auberjonoi [6", "Movie Title":"The Little Mermaid"},
  "Chernabog": { "Voice":"Corey Burton", "Movie Title":"Fantasia"},
  "Cheshire Cat": { "Voice":"Sterling Hollowa [15", "Movie Title":"Alice in Wonderland"},
  "Chi-Fu": { "Voice":"James Hon [46", "Movie Title":"Mulan"},
  "Chicha": { "Voice":"Wendie Malic [41", "Movie Title":"The Emperors New Groove"},
  "Chicken Little": { "Voice":"Zach Braf [1", "Movie Title":"Chicken Little"},
  "Chief": { "Voice":"Pat Buttra [16", "Movie Title":"The Fox and the Hound"},
  "Chief Bogo": { "Voice":"Idris Elba", "Movie Title":"Zootopia"},
  "Chief Powhatan": { "Voice":"Russell Mean [36", "Movie Title":"Pocahontas"},
  "Chien-Po": { "Voice":"Jerry Tond [46", "Movie Title":"Mulan"},
  "Chip": { "Voice":"James MacDonald", "Movie Title":"Private Pluto"},
  "Chip Potts": { "Voice":"Bradley Michael Pierc [25", "Movie Title":"Beauty and the Beast"},
  "Christopher Robin": { "Voice":"Bruce Reitherma [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Cinderella": { "Voice":"Ilene Wood [17", "Movie Title":"Cinderella"},
  "Circus Animals": { "Voice":"None", "Movie Title":"Dumbo"},
  "Clank": { "Voice":"Jeff Bennett", "Movie Title":"Disney Fairies"},
  "Clara Cluck": { "Voice":"Florence Gill", "Movie Title":"Orphans Benefit"},
  "Clarabelle Cow": { "Voice":"Marcellite Garner", "Movie Title":"Plane Crazy"},
  "Clayton": { "Voice":"Brian Blesse [23", "Movie Title":"Tarzan"},
  "Cleo": { "Voice":"None", "Movie Title":"Pinocchio"},
  "Clio": { "Voice":"Vanéese Y. Thoma [14", "Movie Title":"Hercules"},
  "Cloak and Dagger": { "Voice":"None", "Movie Title":"The Little Mermaid II: Return to the Sea"},
  "Clopin Trouillefou": { "Voice":"Paul Kande [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Clotho": { "Voice":"Amanda Plumme [14", "Movie Title":"Hercules"},
  "Clover": { "Voice":"Wayne Brady", "Movie Title":"Sofia the First"},
  "The Coachman": { "Voice":"Charles Judel [38", "Movie Title":"Pinocchio"},
  "Cobra Bubbles": { "Voice":"Ving Rhame [8", "Movie Title":"Lilo & Stitch"},
  "Codfish": { "Voice":"Robert Holt", "Movie Title":"Bedknobs and Broomsticks"},
  "Cody": { "Voice":"Adam Rye [48", "Movie Title":"The Rescuers Down Under"},
  "Cogsworth": { "Voice":"David Ogden Stier [25", "Movie Title":"Beauty and the Beast"},
  "Colette": { "Voice":"Kath Souci [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "The Colonel": { "Voice":"J. Pat OMalle [21", "Movie Title":"101 Dalmatians"},
  "Colonel Hathi": { "Voice":"J. Pat OMalle [9", "Movie Title":"The Jungle Book"},
  "Commander Lyle Rourke": { "Voice":"James Garne [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Cookie": { "Voice":"Jim Varne [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Copper": { "Voice":"Corey Feldma [16 \nKurt Russel [16", "Movie Title":"The Fox and the Hound"},
  "Cornelius Robinson": { "Voice":"Tom Sellec [39", "Movie Title":"Meet the Robinsons"},
  "Cousin Randy": { "Voice":"Randy Newma [42", "Movie Title":"The Princess and the Frog"},
  "Crane": { "Voice":"Jeff Bennett", "Movie Title":"Belles Magical World"},
  "Creeper": { "Voice":"Phil Fondacar [49", "Movie Title":"The Black Cauldron"},
  "Cri-Kee": { "Voice":"None", "Movie Title":"Mulan"},
  "(Tick Tock": { "Voice":"None", "Movie Title":"Peter Pan"},
  "Cruella de Vil    a.k.a. De Vil]": { "Voice":"Betty Lou Gerso [21", "Movie Title":"101 Dalmatians"},
  "Crumbelina DiCaramello": { "Voice":"Cymbre Walk", "Movie Title":"Wreck-It Ralph"},
  "Cubby": { "Voice":"Robert Elli [43", "Movie Title":"Peter Pan"},
  "Cyril Proudbottom": { "Voice":"J. Pat OMalle [20", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Daisy Duck": { "Voice":"Clarence Nash\nGloria Blondell", "Movie Title":"Mr. Duck Steps Out"},
  "Dale": { "Voice":"Dessie Flynn\nCorey Burton", "Movie Title":"Private Pluto"},
  "Dallben": { "Voice":"Freddie Jone [49", "Movie Title":"The Black Cauldron"},
  "Danielle": { "Voice":"Kath Souci [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Danny": { "Voice":"Andrew McDonough", "Movie Title":"Return to Never Land"},
  "Darby": { "Voice":"Chloë Grace Moretz", "Movie Title":"My Friends Tigger & Pooh"},
  "Darling": { "Voice":"Peggy Le [27", "Movie Title":"Lady and the Tramp"},
  "Dash": { "Voice":"Stephen Furst", "Movie Title":"The Little Mermaid II: Return to the Sea"},
  "David Kawena": { "Voice":"Jason Scott Le [8", "Movie Title":"Lilo & Stitch"},
  "Demetrius": { "Voice":"Wayne Knigh [14", "Movie Title":"Hercules"},
  "Denahi": { "Voice":"Jason Raiz [50", "Movie Title":"Brother Bear"},
  "Derek Blunt": { "Voice":"Peter Renaday", "Movie Title":"Darkwing Duck"},
  "DeSoto": { "Voice":"Carl Weintrau [51", "Movie Title":"Oliver & Company"},
  "Dewey": { "Voice":"Clarence Nash\nRussi Taylor", "Movie Title":"Donalds Nephews"},
  "Dex Barrington": { "Voice":"Justin Berfield", "Movie Title":"The Country Bears"},
  "Diablo": { "Voice":"None", "Movie Title":"Sleeping Beauty"},
  "Digger the Mole": { "Voice":"Dub Taylo [37", "Movie Title":"The Rescuers"},
  "Dijon the Thief": { "Voice":"Richard Libertini", "Movie Title":"DuckTales"},
  "Dinah the Cat": { "Voice":"None", "Movie Title":"Alice in Wonderland"},
  "Dinah the Dachshund": { "Voice":"None", "Movie Title":"The Sleepwalker"},
  "Dinky": { "Voice":"Richard Bakalya [16", "Movie Title":"The Fox and the Hound"},
  "The Director": { "Voice":"James Lipto [7", "Movie Title":"Bolt"},
  "Dixie": { "Voice":"Reba McEntire", "Movie Title":"The Fox and the Hound 2"},
  "Dizzie the Vulture": { "Voice":"Lord Tim Hudso [9", "Movie Title":"The Jungle Book"},
  "Djali": { "Voice":"None", "Movie Title":"The Hunchback of Notre Dame"},
  "Doc": { "Voice":"Roy Atwel [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Doctor Mouse": { "Voice":"Bernard Fo [48", "Movie Title":"The Rescuers Down Under"},
  "Dodger": { "Voice":"Billy Joe [51", "Movie Title":"Oliver & Company"},
  "The Dodo": { "Voice":"Bill Thompso [15", "Movie Title":"Alice in Wonderland"},
  "The Dog Catcher": { "Voice":"Jeff Bennet [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Doli": { "Voice":"John Byne [49", "Movie Title":"The Black Cauldron"},
  "Don Karnage": { "Voice":"Jim Cummings", "Movie Title":"TaleSpin"},
  "Donald Duck": { "Voice":"Clarence Nash\nTony Anselmo", "Movie Title":"The Wise Little Hen"},
  "Doofus Drake": { "Voice":"Brian Cummings", "Movie Title":"DuckTales"},
  "The Doorknob": { "Voice":"Joseph Kearn [15", "Movie Title":"Alice in Wonderland"},
  "The Doorman": { "Voice":"Don Barcla [17", "Movie Title":"Cinderella"},
  "Dopey": { "Voice":"Eddie Collin [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Doris": { "Voice":"Ethan Sandle [39", "Movie Title":"Meet the Robinsons"},
  "The Dormouse": { "Voice":"Jimmy MacDonal [15", "Movie Title":"Alice in Wonderland"},
  "Doug Ramses": { "Voice":"Rich Moore", "Movie Title":"Zootopia"},
  "Dr. Calico": { "Voice":"Malcolm McDowel [7", "Movie Title":"Bolt"},
  "Dr. David Q. Dawson": { "Voice":"Val Betti [34", "Movie Title":"The Great Mouse Detective"},
  "Dr. Doppler": { "Voice":"David Hyde Pierc [29", "Movie Title":"Treasure Planet"},
  "Dr. Facilier": { "Voice":"Keith Davi [42", "Movie Title":"The Princess and the Frog"},
  "Dr. Forrester": { "Voice":"Ronn Mos [7", "Movie Title":"Bolt"},
  "Dr. Jacques von Hamsterviel": { "Voice":"Jeff Bennett", "Movie Title":"Stitch! The Movie"},
  "Dr. Joshua Sweet": { "Voice":"Phil Morri [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Dr. Jumba Jookiba": { "Voice":"David Ogden Stier [8", "Movie Title":"Lilo & Stitch"},
  "Dr. Reginald Bushroot": { "Voice":"Tino Insana", "Movie Title":"Darkwing Duck"},
  "Drake Mallard (Darkwing Duck)": { "Voice":"Jim Cummings", "Movie Title":"Darkwing Duck"},
  "Drizella Tremaine": { "Voice":"Rhoda William [17 \nRussi Taylor", "Movie Title":"Cinderella"},
  "Duchess": { "Voice":"Eva Gabo [2", "Movie Title":"The Aristocats"},
  "Duchess": { "Voice":"Marjorie Bennet [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Duckworth": { "Voice":"Chuck McCann", "Movie Title":"DuckTales"},
  "Dug": { "Voice":"Bob Peterson", "Movie Title":"Up"},
  "Duke": { "Voice":"None", "Movie Title":"Fantasia 2000"},
  "Duke of Weselton": { "Voice":"Alan Tudyk", "Movie Title":"Frozen"},
  "Duke Weaselton": { "Voice":"Alan Tudyk", "Movie Title":"Zootopia"},
  "Dumbo": { "Voice":"None", "Movie Title":"Dumbo"},
  "Duncan": { "Voice":"Horatio Sanz", "Movie Title":"Wreck-It Ralph"},
  "Ed": { "Voice":"Jim Cumming [33", "Movie Title":"The Lion King"},
  "Edgar Balthazar the Butler": { "Voice":"Roddy Maude-Roxb [2", "Movie Title":"The Aristocats"},
  "Edward": { "Voice":"Roger Rees", "Movie Title":"Return to Never Land"},
  "Eema": { "Voice":"Della Rees [11", "Movie Title":"Dinosaur"},
  "Eeyore": { "Voice":"Ralph Wrigh [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Einstein": { "Voice":"Richard Mulliga [51", "Movie Title":"Oliver & Company"},
  "El Capitan": { "Voice":"Jim Cummings", "Movie Title":"DuckTales"},
  "Eli ": { "Voice":"John Goodma [42", "Movie Title":"The Princess and the Frog"},
  "Ellie Mae": { "Voice":"Jeanette Nola [37", "Movie Title":"The Rescuers"},
  "Elliott": { "Voice":"Charlie Callas", "Movie Title":"Petes Dragon"},
  "Elmer Elephant": { "Voice":"None", "Movie Title":"Silly Symphonies"},
  "Elsa": { "Voice":"Idina Menzel", "Movie Title":"Frozen"},
  "Emmitt Otterton": { "Voice":"None", "Movie Title":"Zootopia"},
  "Emperor of China": { "Voice":"Pat Morit [46", "Movie Title":"Mulan"},
  "The Enchantress": { "Voice":"Kath Soucie", "Movie Title":"Beauty and the Beast: The Enchanted Christmas"},
  "Esmeralda": { "Voice":"Demi Moor [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Eudora": { "Voice":"Oprah Winfre [42", "Movie Title":"The Princess and the Frog"},
  "Evangaline": { "Voice":"None", "Movie Title":"The Princess and the Frog"},
  "Evinrude": { "Voice":"Jimmy MacDonal [37", "Movie Title":"The Rescuers"},
  "Fa Li": { "Voice":"Freda Foh She [46", "Movie Title":"Mulan"},
  "Fa Zhou": { "Voice":"Soon-Tek O [46", "Movie Title":"Mulan"},
  "Fagin": { "Voice":"Dom DeLuis [51", "Movie Title":"Oliver & Company"},
  "Fairy Godmother": { "Voice":"Verna Felto [17 \nRussi Taylor", "Movie Title":"Cinderella"},
  "Fairy Mary": { "Voice":"Jane Horrocks", "Movie Title":"Disney Fairies"},
  "Faline": { "Voice":"Cammie Kin [32 \nAnn Gilli [32", "Movie Title":"Bambi"},
  "Fall-Apart Rabbit": { "Voice":"Frank Welker", "Movie Title":"Bonkers"},
  "Faloo": { "Voice":"Carla Meye [48", "Movie Title":"The Rescuers Down Under"},
  "Fat Cat": { "Voice":"Jim Cummings", "Movie Title":"Chip n Dale Rescue Rangers"},
  "Father Wolf": { "Voice":"Ben Wrigh [9", "Movie Title":"The Jungle Book"},
  "Fauna": { "Voice":"Barbara Jo Alle [28", "Movie Title":"Sleeping Beauty"},
  "Fawn": { "Voice":"America Ferrera", "Movie Title":"Disney Fairies"},
  "Felicia the Cat": { "Voice":"Frank Welke [34", "Movie Title":"The Great Mouse Detective"},
  "Fenton Crackshell (Gizmoduck)": { "Voice":"Hamilton Camp", "Movie Title":"DuckTales"},
  "Fenton Q. Harcourt": { "Voice":"David Ogden Stier [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Ferdie Fieldmouse": { "Voice":"None", "Movie Title":"Mickeys Steam Roller"},
  "Ferdinand the Bull": { "Voice":"Milt Kahl", "Movie Title":"Silly Symphonies"},
  "Fflewddur Fflam": { "Voice":"Nigel Hawthorn [49", "Movie Title":"The Black Cauldron"},
  "Fidget": { "Voice":"Candy Candid [34", "Movie Title":"The Great Mouse Detective"},
  "Fiddler Pig": { "Voice":"Mary Moder", "Movie Title":"Three Little Pigs"},
  "Fife the Piccolo": { "Voice":"Paul Reubens", "Movie Title":"Beauty and the Beast: The Enchanted Christmas"},
  "Fifer Pig": { "Voice":"Dorothy Compton", "Movie Title":"Three Little Pigs"},
  "Fifi the Featherduster": { "Voice":"Kimmy Robertso [25", "Movie Title":"Beauty and the Beast"},
  "Figaro the Cat": { "Voice":"Mel Blanc", "Movie Title":"Pinocchio"},
  "Figment": { "Voice":"Dave Goelz", "Movie Title":"Journey into Imagination with Figment"},
  "Finnick": { "Voice":"Tommy ", "Movie Title":"Zootopia"},
  "First Ancestor Fa": { "Voice":"George Take [46", "Movie Title":"Mulan"},
  "The Firebird": { "Voice":"Hugo Weaving", "Movie Title":"Fantasia 2000"},
  "Fish Out of Water": { "Voice":"Dan Molin [1", "Movie Title":"Chicken Little"},
  "Fix-It Felix, Jr.": { "Voice":"Jack McBrayer", "Movie Title":"Wreck-It Ralph"},
  "Flaps the Vulture": { "Voice":"Chad Stuar [9", "Movie Title":"The Jungle Book"},
  "Flash Slothmore": { "Voice":"Raymond S. Persi", "Movie Title":"Zootopia"},
  "Flintheart Glomgold": { "Voice":"Hal Smith", "Movie Title":"DuckTales"},
  "Flit": { "Voice":"Frank Welke [36", "Movie Title":"Pocahontas"},
  "Flora": { "Voice":"Verna Felto [28", "Movie Title":"Sleeping Beauty"},
  "Flotsam and Jetsam": { "Voice":"Paddi Edward [6", "Movie Title":"The Little Mermaid"},
  "Flounder": { "Voice":"Jason Mari [6", "Movie Title":"The Little Mermaid"},
  "Flower": { "Voice":"Stan Alexande [32 \nSterling Hollowa [32", "Movie Title":"Bambi"},
  "Flunkey the Baboon": { "Voice":"Leo De Lyo [9", "Movie Title":"The Jungle Book"},
  "Flynn Rider": { "Voice":"Zachary Lev [52", "Movie Title":"Tangled"},
  "Footman": { "Voice":"Larry Grey", "Movie Title":"Cinderella"},
  "Forte the Pipe Organ": { "Voice":"Tim Curry", "Movie Title":"Beauty and the Beast: The Enchanted Christmas"},
  "Foxy Loxy": { "Voice":"Amy Sedari [1", "Movie Title":"Chicken Little"},
  "Fran": { "Voice":"Edie McClurg", "Movie Title":"Higglytown Heroes"},
  "Francis": { "Voice":"Roscoe Lee Brown [51", "Movie Title":"Oliver & Company"},
  "Francois": { "Voice":"Bronson Pincho [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Francois": { "Voice":"Ed Gilber [48", "Movie Title":"The Rescuers Down Under"},
  "Frank": { "Voice":"Wayne Robso [48", "Movie Title":"The Rescuers Down Under"},
  "Frankie the Frog": { "Voice":"Aurian Redso [39", "Movie Title":"Meet the Robinsons"},
  "Franny Robinson": { "Voice":"Nicole Sulliva [39", "Movie Title":"Meet the Robinsons"},
  "Fred": { "Voice":"S. Scott Bullock", "Movie Title":"Timon and Pumbaa"},
  "Friar Tuck": { "Voice":"Andy Devin [13", "Movie Title":"Robin Hood"},
  "Friend Owl": { "Voice":"Will Wrigh [32", "Movie Title":"Bambi"},
  "Frou-Frou": { "Voice":"Nancy Kul [2", "Movie Title":"The Aristocats"},
  "Gadget Hackwrench": { "Voice":"Tress MacNeille", "Movie Title":"Chip n Dale Rescue Rangers"},
  "Gaetan ": { "Voice":"Corey Burto [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Captain Gantu": { "Voice":"Kevin Michael Richardso [8", "Movie Title":"Lilo & Stitch"},
  "Gaston": { "Voice":"Richard Whit [25", "Movie Title":"Beauty and the Beast"},
  "Gazelle": { "Voice":"Shakira", "Movie Title":"Zootopia"},
  "General Hologram": { "Voice":"Dennis Haysbert", "Movie Title":"Wreck-It Ralph"},
  "General Li": { "Voice":"James Shiget [46", "Movie Title":"Mulan"},
  "Genie": { "Voice":"Robin William [4", "Movie Title":"Aladdin"},
  "George Darling": { "Voice":"Hans Conrie [43", "Movie Title":"Peter Pan"},
  "Georges Hautecourt": { "Voice":"Charles Lan [2", "Movie Title":"The Aristocats"},
  "Georgette": { "Voice":"Bette Midle [51", "Movie Title":"Oliver & Company"},
  "Geppetto": { "Voice":"Christian Ru [38", "Movie Title":"Pinocchio"},
  "Giddy the Elephant": { "Voice":"Dorothy Scot [44", "Movie Title":"Dumbo"},
  "Gideon": { "Voice":"Mel Blan [38", "Movie Title":"Pinocchio"},
  "Giselle": { "Voice":"Amy Adams", "Movie Title":"Enchanted"},
  "Gladstone Gander": { "Voice":"Rob Paulsen", "Movie Title":"DuckTales"},
  "Gliss": { "Voice":"Grey DeLisle", "Movie Title":"Secret of the Wings"},
  "Glittering Goldie": { "Voice":"Joan Gerber", "Movie Title":"DuckTales"},
  "Gloyd Orangeboar": { "Voice":"None", "Movie Title":"Wreck-It Ralph"},
  "Goob": { "Voice":"Matthew Joste [39", "Movie Title":"Meet the Robinsons"},
  "Goofy": { "Voice":"Pinto Colvig\nBill Farmer", "Movie Title":"Mickeys Revue"},
  "Goosey Loosey": { "Voice":"Mark Walto [1", "Movie Title":"Chicken Little"},
  "Gopher": { "Voice":"Howard Morris\nMichael Goug [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Gosalyn Mallard": { "Voice":"Christine Cavanaugh", "Movie Title":"Darkwing Duck"},
  "Governor John Ratcliffe": { "Voice":"David Ogden Stier [36", "Movie Title":"Pocahontas"},
  "Grace": { "Voice":"Jennifer Till [12", "Movie Title":"Home on the Range"},
  "Gramma Tala": { "Voice":"Rachel House", "Movie Title":"Moana"},
  "Gramps": { "Voice":"Larry Clemmon [37", "Movie Title":"The Rescuers"},
  "Grand Councilwoman": { "Voice":"Zoe Caldwel [8", "Movie Title":"Lilo & Stitch"},
  "The Grand Duke": { "Voice":"Luis van Roote [17 \nRob Paulsen", "Movie Title":"Cinderella"},
  "Grandma Duck": { "Voice":"June Foray", "Movie Title":"This is Your Life, Donald Duck"},
  "Grandmother Fa": { "Voice":"June Fora [46", "Movie Title":"Mulan"},
  "Grandmother Willow": { "Voice":"Linda Hun [36", "Movie Title":"Pocahontas"},
  "Granny Rose": { "Voice":"Vicki Lawrence", "Movie Title":"The Fox and the Hound 2"},
  "Greasy the Weasel": { "Voice":"Charles Fleische [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Great Prince of the Forest": { "Voice":"Fred Shield [32", "Movie Title":"Bambi"},
  "Grimsby": { "Voice":"Ben Wrigh [6", "Movie Title":"The Little Mermaid"},
  "The Groundhog": { "Voice":"Brian Pimental", "Movie Title":"Bambi II"},
  "Grumpy": { "Voice":"Pinto Colvi [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Gurgi": { "Voice":"John Byne [49", "Movie Title":"The Black Cauldron"},
  "Gus Lollygagger": { "Voice":"Jimmy MacDonal [17 \nCorey Burton", "Movie Title":"Cinderella"},
  "Gus Goose": { "Voice":"Clarence Nash", "Movie Title":"Donalds Cousin Gus"},
  "Gyro Gearloose": { "Voice":"Hal Smith", "Movie Title":"DuckTales"},
  "Hades": { "Voice":"James Wood [14", "Movie Title":"Hercules"},
  "Hands": { "Voice":"Michael McShan [29", "Movie Title":"Treasure Planet"},
  "Happy": { "Voice":"Otis Harla [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Harold the Seahorse": { "Voice":"Will Rya [6", "Movie Title":"The Little Mermaid"},
  "Haroud Hazi Bin": { "Voice":"James Avery", "Movie Title":"Aladdin (TV series)"},
  "Harvey Fenner": { "Voice":"Corey Burto [42", "Movie Title":"The Princess and the Frog"},
  "Headless Horseman": { "Voice":"None", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Heihei the Rooster": { "Voice":"Alan Tudyk", "Movie Title":"Moana"},
  "Helga Sinclair": { "Voice":"Claudia Christia [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Hen Wen": { "Voice":"None", "Movie Title":"The Black Cauldron"},
  "Henry Fenner": { "Voice":"Jerry Kernio [42", "Movie Title":"The Princess and the Frog"},
  "Hera": { "Voice":"Samantha Egga [14", "Movie Title":"Hercules"},
  "Herb Muddlefoot": { "Voice":"Jim Cummings", "Movie Title":"Darkwing Duck"},
  "Hercules": { "Voice":"Tate Donova [14 \nJoshua Keato [14", "Movie Title":"Hercules"},
  "Hermes": { "Voice":"Paul Shaffe [14", "Movie Title":"Hercules"},
  "Hiram Flaversham": { "Voice":"Alan Youn [34", "Movie Title":"The Great Mouse Detective"},
  "Hit Cat the English Cat": { "Voice":"Lord Tim Hudso [2", "Movie Title":"The Aristocats"},
  "Honker Muddlefoot": { "Voice":"Katie Leigh", "Movie Title":"Darkwing Duck"},
  "Hook Hand": { "Voice":"Brad Garret [52", "Movie Title":"Tangled"},
  "Hoonah": { "Voice":"Tress MacNeill [18", "Movie Title":"Brother Bear 2"},
  "Horace & Jasper": { "Voice":"Frederick Worloc [21 \nJ. Pat OMalle [21", "Movie Title":"101 Dalmatians"},
  "Horace Horsecollar": { "Voice":"Walt Disney\nBill Farmer", "Movie Title":"The Plow Boy"},
  "The Horned King": { "Voice":"John Hur [49", "Movie Title":"The Black Cauldron"},
  "Huey": { "Voice":"Clarence Nash\nRussi Taylor", "Movie Title":"Donalds Nephews"},
  "Hugo": { "Voice":"Jason Alexande [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Humbert the Huntsman": { "Voice":"Stuart Buchana [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Humphrey the Bear": { "Voice":"Jimmy MacDonald\nJim Cummings", "Movie Title":"Hold That Pose"},
  "Hyacinth Hippo": { "Voice":"Tress MacNeille", "Movie Title":"Fantasia"},
  "Iago": { "Voice":"Gilbert Gottfrie [4", "Movie Title":"Aladdin"},
  "Ian the Alligator": { "Voice":"Kevin Michael Richardso [42", "Movie Title":"The Princess and the Frog"},
  "Ichabod Crane": { "Voice":"Pinto Colvig", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "The Indian Chief": { "Voice":"Candy Candid [43", "Movie Title":"Peter Pan"},
  "Innoko": { "Voice":"Wanda Syke [18", "Movie Title":"Brother Bear 2"},
  "Iridessa": { "Voice":"Raven-Symoné", "Movie Title":"Disney Fairies"},
  "J. Audubon Woodlore": { "Voice":"Bill Thompson", "Movie Title":"Grin and Bear It"},
  "J. Gander Hooter": { "Voice":"Danny Mann", "Movie Title":"Darkwing Duck"},
  "J. Thaddeus Toad": { "Voice":"Eric Blor [20", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "J. Worthington Foulfellow": { "Voice":"Walter Catlet [38", "Movie Title":"Pinocchio"},
  "Jack-in-the-Box": { "Voice":"John Lithgow", "Movie Title":"Fantasia 2000"},
  "Jackson ": { "Voice":"Jimmy MacDonal [17 \nRob Paulsen", "Movie Title":"Cinderella"},
  "Jafar": { "Voice":"Jonathan Freema [4", "Movie Title":"Aladdin"},
  "Jake": { "Voice":"Tristan Roger [48", "Movie Title":"The Rescuers Down Under"},
  "Jane": { "Voice":"Harriet Owen", "Movie Title":"Return to Never Land"},
  "Jane Porter": { "Voice":"Minnie Drive [23", "Movie Title":"Tarzan"},
  "Jeb the Goat": { "Voice":"Joe Flahert [12", "Movie Title":"Home on the Range"},
  "Jennifer ": { "Voice":"Natalie Gregor [51", "Movie Title":"Oliver & Company"},
  "Jenny Wren": { "Voice":"Martha Wentworth", "Movie Title":"Silly Symphonies"},
  "Jerry Jumbeaux Jr.": { "Voice":"John DiMaggio", "Movie Title":"Zootopia"},
  "Jesse the Ram": { "Voice":"John DiMaggio", "Movie Title":"Zootopia"},
  "Jessica Rabbit": { "Voice":"Kathleen Turne [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Jim Crow": { "Voice":"Cliff Edward [44", "Movie Title":"Dumbo"},
  "Jim Dear": { "Voice":"Lee Milla [27", "Movie Title":"Lady and the Tramp"},
  "Jim Hawkins": { "Voice":"Joseph Gordon-Levit [29", "Movie Title":"Treasure Planet"},
  "Jiminy Cricket": { "Voice":"Cliff Edward [38 \nEddie Carroll", "Movie Title":"Pinocchio"},
  "Jobless Joe": { "Voice":"None", "Movie Title":"Fantasia 2000"},
  "Jock": { "Voice":"Bill Thompso [27", "Movie Title":"Lady and the Tramp"},
  "Joe Giraffe": { "Voice":"Pinto Colvi [53", "Movie Title":"Silly Symphonies"},
  "Joey Hippo": { "Voice":"None", "Movie Title":"Silly Symphonies"},
  "John Darling": { "Voice":"Paul Collin [43", "Movie Title":"Peter Pan"},
  "John Silver": { "Voice":"Brian Murra [29", "Movie Title":"Treasure Planet"},
  "Johnny Appleseed": { "Voice":"Dennis Day", "Movie Title":"Melody Time"},
  "José Carioca": { "Voice":"José Oliveir [54 \nRob Paulsen", "Movie Title":"Saludos Amigos"},
  "Jubileena Bing-Bing": { "Voice":"Josie Trinidad", "Movie Title":"Wreck-It Ralph"},
  "Judge Claude Frollo": { "Voice":"Tony Ja [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Judge Doom": { "Voice":"Christopher Lloy [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Judy Hopps": { "Voice":"Ginnifer Goodwin", "Movie Title":"Zootopia"},
  "June": { "Voice":"None", "Movie Title":"House of Mouse"},
  "Junior": { "Voice":"Clint Howar [9", "Movie Title":"The Jungle Book"},
  "Junior the Buffalo": { "Voice":"Lance LeGaul [12", "Movie Title":"Home on the Range"},
  "Kaa": { "Voice":"Sterling Hollowa [9 \nJim Cummings", "Movie Title":"The Jungle Book"},
  "Kala": { "Voice":"Glenn Clos [23", "Movie Title":"Tarzan"},
  "Kanga": { "Voice":"Barbara Ludd [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Kata": { "Voice":"Catherine OHar [18", "Movie Title":"Brother Bear 2"},
  "Katrina Van Tassel": { "Voice":"None", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Kekata the Medicine man": { "Voice":"Gordon Tootoosi [36", "Movie Title":"Pocahontas"},
  "Kenai": { "Voice":"Joaquin Phoeni [50", "Movie Title":"Brother Bear"},
  "Kerchak": { "Voice":"Lance Henrikse [23", "Movie Title":"Tarzan"},
  "Kiara": { "Voice":"Michelle Horn\nNeve Campbell", "Movie Title":"The Lion King II: Simbas Pride"},
  "The King": { "Voice":"Luis Van Roote [17", "Movie Title":"Cinderella"},
  "The King of Hearts": { "Voice":"Dink Trou [15", "Movie Title":"Alice in Wonderland"},
  "King Candy/Turbo": { "Voice":"Alan Tudyk", "Movie Title":"Wreck-It Ralph"},
  "King Eiddileg": { "Voice":"Arthur Male [49", "Movie Title":"The Black Cauldron"},
  "King Hubert": { "Voice":"Bill Thompso [28", "Movie Title":"Sleeping Beauty"},
  "King Kashekim Nedakh": { "Voice":"Leonard Nimo [26", "Movie Title":"Atlantis: The Lost Empire"},
  "King Leonidas": { "Voice":"Lennie Weinrib", "Movie Title":"Bedknobs and Broomsticks"},
  "King Louie": { "Voice":"Louis Prim [9", "Movie Title":"The Jungle Book"},
  "King Richard": { "Voice":"Peter Ustino [13", "Movie Title":"Robin Hood"},
  "King Roland II": { "Voice":"Travis Willingham", "Movie Title":"Sofia the First"},
  "King Stefan": { "Voice":"Taylor Holme [28", "Movie Title":"Sleeping Beauty"},
  "King Triton": { "Voice":"Kenneth Mar [6", "Movie Title":"The Little Mermaid"},
  "Kirby": { "Voice":"Sean Elmor [1 \nMatthew Josto [1 Evan Dun [1", "Movie Title":"Chicken Little"},
  "Kit Cloudkicker": { "Voice":"R. J. Williams\nAlan Roberts", "Movie Title":"TaleSpin"},
  "Kocoum": { "Voice":"James Apaumut Fal [36", "Movie Title":"Pocahontas"},
  "Koda": { "Voice":"Jeremy Suare [50", "Movie Title":"Brother Bear"},
  "Kovu": { "Voice":"Ryan ODonohue\nJason Marsden", "Movie Title":"The Lion King II: Simbas Pride"},
  "Krebbs": { "Voice":"Douglas Seal [48", "Movie Title":"The Rescuers Down Under"},
  "Kristoff": { "Voice":"Jonathan Groff", "Movie Title":"Frozen"},
  "Kron": { "Voice":"Samuel E. Wrigh [11", "Movie Title":"Dinosaur"},
  "Kronk Pepikrankenitz": { "Voice":"Patrick Warburto [41", "Movie Title":"The Emperors New Groove"},
  "Kuzco": { "Voice":"David Spad [41", "Movie Title":"The Emperors New Groove"},
  "Lachesis": { "Voice":"Carole Shelle [14", "Movie Title":"Hercules"},
  "Lady": { "Voice":"Barbara Ludd [27", "Movie Title":"Lady and the Tramp"},
  "Lady DeBurne": { "Voice":"April Winchel [55", "Movie Title":"The Hunchback of Notre Dame II"},
  "Lady Kluck": { "Voice":"Carole Shelle [13", "Movie Title":"Robin Hood"},
  "Lady Mouse": { "Voice":"Shani Walli [34", "Movie Title":"The Great Mouse Detective"},
  "Lady Tremaine": { "Voice":"Eleanor Audle [17 \nSusanne Blakeslee", "Movie Title":"Cinderella"},
  "Lafayette the Basset Hound": { "Voice":"George Lindse [2", "Movie Title":"The Aristocats"},
  "Lampwick": { "Voice":"Frankie Darr [38", "Movie Title":"Pinocchio"},
  "Larry the Duck": { "Voice":"Marshall Efro [12", "Movie Title":"Home on the Range"},
  "Launchpad McQuack": { "Voice":"Terry McGovern", "Movie Title":"DuckTales"},
  "Laverne": { "Voice":"Mary Wicke [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Lawrence the Valet": { "Voice":"Peter Bartlet [42", "Movie Title":"The Princess and the Frog"},
  "Le Fou": { "Voice":"Jesse Cort [25", "Movie Title":"Beauty and the Beast"},
  "Lefty": { "Voice":"Nathan Gren [39", "Movie Title":"Meet the Robinsons"},
  "Leonard Helperman": { "Voice":"Shaun Flemin [56", "Movie Title":"Teachers Pet"},
  "Le Plufme": { "Voice":"Rob Paulsen", "Movie Title":"Belles Magical World"},
  "Lewis": { "Voice":"Jordan Fr [39", "Movie Title":"Meet the Robinsons"},
  "Li Shang": { "Voice":"B.D. Won [46", "Movie Title":"Mulan"},
  "Lil Bad Wolf": { "Voice":"Andrew Lawrence", "Movie Title":"The Porkers Court"},
  "Lilo Pelekai": { "Voice":"Daveigh Chas [8", "Movie Title":"Lilo & Stitch"},
  "Ling": { "Voice":"Gedde Watanab [46", "Movie Title":"Mulan"},
  "The Liquidator": { "Voice":"Jack Angel", "Movie Title":"Darkwing Duck"},
  "Little John": { "Voice":"Phil Harri [13", "Movie Title":"Robin Hood"},
  "Little Toot": { "Voice":"None", "Movie Title":"Melody Time"},
  "Mr. Litwak": { "Voice":"Ed ONeill", "Movie Title":"Wreck-It Ralph"},
  "Lizzy": { "Voice":"Tracey Miller-Zarnek [39", "Movie Title":"Meet the Robinsons"},
  "Lizzy Griffths": { "Voice":"Lauren Mot [57", "Movie Title":"Tinker Bell and the Great Fairy Rescue"},
  "Louie": { "Voice":"Clarence Nash\nRussi Taylor", "Movie Title":"Donalds Nephews"},
  "Louie the Hot Dog Man": { "Voice":"Frank Welke [51", "Movie Title":"Oliver & Company"},
  "Louis the Alligator": { "Voice":"Michael-Leon Woole [42", "Movie Title":"The Princess and the Frog"},
  "Lucifer the Cat": { "Voice":"June Fora [17", "Movie Title":"Cinderella"},
  "Lucille Krunklehorn": { "Voice":"Laurie Metcal [39", "Movie Title":"Meet the Robinsons"},
  "Lucky": { "Voice":"Mimi Gibso [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Lucky Jack": { "Voice":"Charles Hai [12", "Movie Title":"Home on the Range"},
  "Ludwig Von Drake": { "Voice":"Paul Frees", "Movie Title":"An Adventure In Color"},
  "Luke": { "Voice":"Pat Buttra [37", "Movie Title":"The Rescuers"},
  "Lumière": { "Voice":"Jerry Orbac [25", "Movie Title":"Beauty and the Beast"},
  "Lumpy the Heffalump": { "Voice":"Kyle Stanger", "Movie Title":"Poohs Heffalump Movie"},
  "Lyle": { "Voice":"Jeff Foxworthy", "Movie Title":"The Fox and the Hound 2"},
  "Ma Beagle": { "Voice":"June Foray", "Movie Title":"DuckTales"},
  "Mad Hatter": { "Voice":"Ed Wyn [15", "Movie Title":"Alice in Wonderland"},
  "Madame Adelaide Bonfamille": { "Voice":"Hermione Baddele [2", "Movie Title":"The Aristocats"},
  "Madame Medusa": { "Voice":"Geraldine Pag [37", "Movie Title":"The Rescuers"},
  "Madam Mim": { "Voice":"Martha Wentwort [24", "Movie Title":"The Sword in the Stone"},
  "Madame Upanova": { "Voice":"Tress MacNeille", "Movie Title":"Fantasia"},
  "Madellaine": { "Voice":"Jennifer Love Hewit [55", "Movie Title":"The Hunchback of Notre Dame II"},
  "Maggie": { "Voice":"Roseanne Bar [12", "Movie Title":"Home on the Range"},
  "Magic Carpet": { "Voice":"None", "Movie Title":"Aladdin"},
  "The Magic Mirror": { "Voice":"Moroni Olse [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Magica De Spell": { "Voice":"June Foray", "Movie Title":"DuckTales"},
  "Mahra the Baboon": { "Voice":"Tress MacNeille", "Movie Title":"Jungle Cubs"},
  "Maid Marian": { "Voice":"Monica Evan [13", "Movie Title":"Robin Hood"},
  "Major the Horse": { "Voice":"None", "Movie Title":"Cinderella"},
  "Maleficent": { "Voice":"Eleanor Audle [28", "Movie Title":"Sleeping Beauty"},
  "Malina": { "Voice":"Jessica DiCicco", "Movie Title":"The Emperors New School"},
  "Mama Heffalump": { "Voice":"Brenda Blethyn", "Movie Title":"Poohs Heffalump Movie"},
  "Mama Odie": { "Voice":"Jenifer Lewi [42", "Movie Title":"The Princess and the Frog"},
  "Man the Hunter": { "Voice":"None", "Movie Title":"Bambi"},
  "Marahute": { "Voice":"Frank Welke [48", "Movie Title":"The Rescuers Down Under"},
  "March Hare": { "Voice":"Jerry Colonn [15", "Movie Title":"Alice in Wonderland"},
  "Marie": { "Voice":"Liz Englis [2", "Movie Title":"The Aristocats"},
  "Markowski": { "Voice":"Joe Lo Truglio", "Movie Title":"Wreck-It Ralph"},
  "Marlon the Alligator": { "Voice":"Emeril Lagass [42", "Movie Title":"The Princess and the Frog"},
  "Mary Darling": { "Voice":"Heather Ange [43", "Movie Title":"Peter Pan"},
  "The Matchmaker": { "Voice":"Miriam Margolye [46", "Movie Title":"Mulan"},
  "Maui": { "Voice":"Dwayne Johnson", "Movie Title":"Moana"},
  "Maurice": { "Voice":"Rex Everhar [25", "Movie Title":"Beauty and the Beast"},
  "Max Goof": { "Voice":"Dana Hill\nJason Marsden", "Movie Title":"Goof Troop"},
  "Max Hare": { "Voice":"Ned Norto [58", "Movie Title":"The Tortoise and the Hare"},
  "Max the Sheepdog": { "Voice":"Frank Welke [6", "Movie Title":"The Little Mermaid"},
  "Maximus": { "Voice":"None", "Movie Title":"Tangled"},
  "May": { "Voice":"None", "Movie Title":"House of Mouse"},
  "Mayor Lionheart": { "Voice":"J. K. Simmons", "Movie Title":"Zootopia"},
  "Mechanicles": { "Voice":"Charlie Adler", "Movie Title":"Aladdin (TV series)"},
  "Meeko": { "Voice":"John Kassi [36", "Movie Title":"Pocahontas"},
  "Megabyte Beagle": { "Voice":"Frank Welker", "Movie Title":"DuckTales"},
  "Megara": { "Voice":"Susan Ega [14", "Movie Title":"Hercules"},
  "Megavolt": { "Voice":"Dan Castellaneta", "Movie Title":"Darkwing Duck"},
  "Melody": { "Voice":"Tara Strong", "Movie Title":"The Little Mermaid II: Return to the Sea"},
  "Melinda": { "Voice":"None", "Movie Title":"Fantasia"},
  "Melpomene": { "Voice":"Cheryl Freema [14", "Movie Title":"Hercules"},
  "Melvin": { "Voice":"Fred Willar [1", "Movie Title":"Chicken Little"},
  "Mena": { "Voice":"Cree Summer", "Movie Title":"Bambi II"},
  "Merlin": { "Voice":"Karl Swenso [24", "Movie Title":"The Sword in the Stone"},
  "Merlock the Magician": { "Voice":"Christopher Lloyd", "Movie Title":"DuckTales"},
  "Merryweather": { "Voice":"Barbara Ludd [28", "Movie Title":"Sleeping Beauty"},
  "Michael Darling": { "Voice":"Tommy Lusk [43", "Movie Title":"Peter Pan"},
  "Mickey Mouse": { "Voice":"Walt Disney", "Movie Title":"Steamboat Willie"},
  "Mike the Microphone": { "Voice":"Rod Roddy", "Movie Title":"House of Mouse"},
  "Mildred": { "Voice":"Angela Basset [39", "Movie Title":"Meet the Robinsons"},
  "Milo Thatch": { "Voice":"Michael J. Fo [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Mindy": { "Voice":"Kari Wahlgre [7", "Movie Title":"Bolt"},
  "Minnie Mouse": { "Voice":"Walt Disney\nMarcellite Garner", "Movie Title":"Plane Crazy"},
  "Minty Zaki": { "Voice":"None", "Movie Title":"Wreck-It Ralph"},
  "Mirage": { "Voice":"Bebe Neuwirth", "Movie Title":"Aladdin (TV series)"},
  "Miranda Wright": { "Voice":"Karla DeVito", "Movie Title":"Bonkers"},
  "Miss Bianca": { "Voice":"Eva Gabo [37", "Movie Title":"The Rescuers"},
  "Miss Kitty": { "Voice":"Melissa Mancheste [34", "Movie Title":"The Great Mouse Detective"},
  "Miss Nettle": { "Voice":"Megan Mullally", "Movie Title":"Sofia the First"},
  "Mittens": { "Voice":"Susie Essma [7", "Movie Title":"Bolt"},
  "Moana": { "Voice":"Aulii Cravalho", "Movie Title":"Moana"},
  "Moley": { "Voice":"Colin Campbel [20", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Monsieur DArque": { "Voice":"Tony Ja [25", "Movie Title":"Beauty and the Beast"},
  "Monstro": { "Voice":"Thurl Ravenscroft", "Movie Title":"Pinocchio"},
  "Monterey Jack": { "Voice":"Jim Cummings", "Movie Title":"Chip n Dale Rescue Rangers"},
  "Mooch": { "Voice":"Bill Fagerbakk [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Morcupine Porcupine": { "Voice":"Mark Dinda [1", "Movie Title":"Chicken Little"},
  "Morgana": { "Voice":"Pat Carroll", "Movie Title":"The Little Mermaid II: Return to the Sea"},
  "Morgana McCawber": { "Voice":"Kath Soucie", "Movie Title":"Darkwing Duck"},
  "Morph": { "Voice":"Dane A. Davi [29", "Movie Title":"Treasure Planet"},
  "Mortimer Mouse": { "Voice":"Maurice LaMarche", "Movie Title":"Mickeys Rival"},
  "Morty Fieldmouse": { "Voice":"None", "Movie Title":"Mickeys Steam Roller"},
  "Mother Gothel": { "Voice":"Donna Murph [52", "Movie Title":"Tangled"},
  "Mother Rabbit": { "Voice":"Barbara Ludd [13", "Movie Title":"Robin Hood"},
  "Mowgli": { "Voice":"Bruce Reitherma [9", "Movie Title":"The Jungle Book"},
  "Mozenrath": { "Voice":"Jonathan Brandis", "Movie Title":"Aladdin (TV series)"},
  "Mr. Arrow": { "Voice":"Roscoe Lee Brown [29", "Movie Title":"Treasure Planet"},
  "Mr. Big": { "Voice":"Maurice LaMarche", "Movie Title":"Zootopia"},
  "Mr. Jolly": { "Voice":"David Ogden Stiers", "Movie Title":"Teachers Pet"},
  "Mr. Pettibone": { "Voice":"Jeff Pidgeon", "Movie Title":"Mickey Mouse Clubhouse"},
  "Mr. Smee": { "Voice":"Bill Thompso [43", "Movie Title":"Peter Pan"},
  "Mr. Snoops": { "Voice":"Joe Flyn [37", "Movie Title":"The Rescuers"},
  "Mr. Stork": { "Voice":"Sterling Hollowa [44", "Movie Title":"Dumbo"},
  "Mr. Willerstein": { "Voice":"Tom Kenn [39", "Movie Title":"Meet the Robinsons"},
  "Mr. Woolensworth": { "Voice":"Patrick Stewar [1", "Movie Title":"Chicken Little"},
  "Mrs. Calloway": { "Voice":"Judi Denc [12", "Movie Title":"Home on the Range"},
  "Mrs. Featherby": { "Voice":"June Foray", "Movie Title":"DuckTales"},
  "Mrs. Hasagawa": { "Voice":"Amy Hil [8", "Movie Title":"Lilo & Stitch"},
  "Mrs. Judson": { "Voice":"Diana Chesne [34", "Movie Title":"The Great Mouse Detective"},
  "Mrs. Jumbo": { "Voice":"Verna Felto [44", "Movie Title":"Dumbo"},
  "Mrs. Otterton": { "Voice":"Octavia Spencer", "Movie Title":"Zootopia"},
  "Mrs. Possum": { "Voice":"Mary Lansin [32", "Movie Title":"Bambi"},
  "Mrs. Potts": { "Voice":"Angela Lansbur [25", "Movie Title":"Beauty and the Beast"},
  "Mrs. Quail": { "Voice":"Thelma Boardma [32", "Movie Title":"Bambi"},
  "Mufasa": { "Voice":"James Earl Jone [33", "Movie Title":"The Lion King"},
  "Mulan": { "Voice":"Ming-Na Wen\nLea Salong [46", "Movie Title":"Mulan"},
  "Mungo": { "Voice":"Jason Marsde [23", "Movie Title":"Tarzan"},
  "Mushu": { "Voice":"Eddie Murph [46", "Movie Title":"Mulan"},
  "Myrtle Edmonds": { "Voice":"Miranda Paige Wall [8 \nLiliana Mumy", "Movie Title":"Lilo & Stitch"},
  "Nakoma": { "Voice":"Michelle St. Joh [36", "Movie Title":"Pocahontas"},
  "Nala": { "Voice":"Moira Kell [33 \nNiketa Calam [33", "Movie Title":"The Lion King"},
  "Nana": { "Voice":"None", "Movie Title":"Peter Pan"},
  "Nancy Tremaine": { "Voice":"Idina Menzel", "Movie Title":"Enchanted"},
  "Nani Pelekai": { "Voice":"Tia Carrer [8", "Movie Title":"Lilo & Stitch"},
  "Nanny": { "Voice":"Martha Wentwort [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Napoleon the Bloodhound": { "Voice":"Pat Buttra [2", "Movie Title":"The Aristocats"},
  "Nasira": { "Voice":"Jodi Benson", "Movie Title":"Aladdin in Nasiras Revenge"},
  "Nathaniel": { "Voice":"Timothy Spall", "Movie Title":"Enchanted"},
  "Natives": { "Voice":"Jeff Bennett", "Movie Title":"Timon and Pumbaa"},
  "Ned the Baboon": { "Voice":"Charlie Adler", "Movie Title":"Jungle Cubs"},
  "Neera": { "Voice":"Julianna Margulie [11", "Movie Title":"Dinosaur"},
  "NegaDuck": { "Voice":"Jim Cummings", "Movie Title":"Darkwing Duck"},
  "Nessus": { "Voice":"Jim Cumming [14", "Movie Title":"Hercules"},
  "Nibs": { "Voice":"Jeffrey Silve [43", "Movie Title":"Peter Pan"},
  "Nicholas ": { "Voice":"Jason Bateman", "Movie Title":"Zootopia"},
  "Nita": { "Voice":"Mandy Moor [18", "Movie Title":"Brother Bear 2"},
  "Nuka": { "Voice":"Andy Dick", "Movie Title":"The Lion King II: Simbas Pride"},
  "Nurse Mouse": { "Voice":"Russi Taylo [48", "Movie Title":"The Rescuers Down Under"},
  "Nutsy the Vulture": { "Voice":"Ken Curti [13", "Movie Title":"Robin Hood"},
  "Oaken": { "Voice":"Chris Williams", "Movie Title":"Frozen"},
  "The Octopus": { "Voice":"Frank Welker", "Movie Title":"Return to Never Land"},
  "Olaf": { "Voice":"Josh Gad", "Movie Title":"Frozen"},
  "Oliver": { "Voice":"Joey Lawrenc [51", "Movie Title":"Oliver & Company"},
  "Olivia Flaversham": { "Voice":"Susanne Pollatsche [34", "Movie Title":"The Great Mouse Detective"},
  "Ollie the Pig": { "Voice":"Charlie Del [12", "Movie Title":"Home on the Range"},
  "Onus": { "Voice":"Corey Burto [29", "Movie Title":"Treasure Planet"},
  "Orddu": { "Voice":"Eda Reiss Meri [49", "Movie Title":"The Black Cauldron"},
  "Orgoch": { "Voice":"Billie Haye [49", "Movie Title":"The Black Cauldron"},
  "Orville": { "Voice":"Jim Jorda [37", "Movie Title":"The Rescuers"},
  "Orwen": { "Voice":"Adele Malis-More [49", "Movie Title":"The Black Cauldron"},
  "Oswald the Lucky Rabbit": { "Voice":"Frank Welker", "Movie Title":"Trolley Troubles"},
  "Otto": { "Voice":"J. Pat OMalle [13", "Movie Title":"Robin Hood"},
  "Owl": { "Voice":"Hal Smit [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Pacha": { "Voice":"John Goodma [41", "Movie Title":"The Emperors New Groove"},
  "Pain and Panic": { "Voice":"Bobcat Goldthwai [14 \nMatt Frewe [14", "Movie Title":"Hercules"},
  "Panchito Pistoles": { "Voice":"Joaquin Gara [22 \nCarlos Alazraqui", "Movie Title":"The Three Caballeros"},
  "Pascal": { "Voice":"Frank Welker", "Movie Title":"Tangled"},
  "Patch": { "Voice":"Mickey Mag [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Pearl Gesner": { "Voice":"Carole Coo [12", "Movie Title":"Home on the Range"},
  "Peg": { "Voice":"Peggy Le [27", "Movie Title":"Lady and the Tramp"},
  "Peg Pete": { "Voice":"April Winchell", "Movie Title":"Goof Troop"},
  "Pegasus": { "Voice":"Frank Welker", "Movie Title":"Hercules"},
  "Pennys Mom": { "Voice":"Grey DeLisl [7", "Movie Title":"Bolt"},
  "Penny": { "Voice":"Sandra Abbot [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Penny": { "Voice":"Michelle Stac [37", "Movie Title":"The Rescuers"},
  "Penny": { "Voice":"Miley Cyru [7", "Movie Title":"Bolt"},
  "Pepper Ann Pearson": { "Voice":"Kathleen Wilhoite", "Movie Title":"Pepper Ann"},
  "Peppo the Italian Cat": { "Voice":"Vito Scott [2", "Movie Title":"The Aristocats"},
  "Percival C. McLeach": { "Voice":"George C. Scot [48", "Movie Title":"The Rescuers Down Under"},
  "Percy": { "Voice":"Danny Man [36", "Movie Title":"Pocahontas"},
  "Perdita": { "Voice":"Cate Baue [21", "Movie Title":"101 Dalmatians"},
  "Periwinkle": { "Voice":"Lucy Hal [59", "Movie Title":"Secret of the Wings"},
  "Pete": { "Voice":"Billy Bletcher\nJim Cummings", "Movie Title":"Alice Solves the Puzzle"},
  "Pete Junior": { "Voice":"Rob Paulsen", "Movie Title":"Goof Troop"},
  "Peter Pan": { "Voice":"Bobby Driscol [43", "Movie Title":"Peter Pan"},
  "Peter Pig": { "Voice":"Pinto Colvig", "Movie Title":"The Wise Little Hen"},
  "The Phantom Blot": { "Voice":"Frank Welker", "Movie Title":"DuckTales"},
  "Philoctetes": { "Voice":"Danny DeVit [14", "Movie Title":"Hercules"},
  "Philippe the Horse": { "Voice":"Hal Smit [25", "Movie Title":"Beauty and the Beast"},
  "Piglet": { "Voice":"John Fiedle [47", "Movie Title":"Winnie the Pooh and the Blustery Day"},
  "Pinocchio": { "Voice":"Dickie Jone [38", "Movie Title":"Pinocchio"},
  "Pip": { "Voice":"Jeff Bennett\nKevin Lima", "Movie Title":"Enchanted"},
  "Pistol Pete": { "Voice":"Nancy Cartwright", "Movie Title":"Goof Troop"},
  "Plio": { "Voice":"Alfre Woodar [11", "Movie Title":"Dinosaur"},
  "Pluto": { "Voice":"Pinto Colvig\nBill Farmer", "Movie Title":"The Chain Gang"},
  "Pocahontas": { "Voice":"Irene Bedard\nJudy Kuh [36", "Movie Title":"Pocahontas"},
  "Poe De Spell": { "Voice":"Terry McGovern\nFrank Welker", "Movie Title":"DuckTales"},
  "Pom-Pom": { "Voice":"Frank Welker", "Movie Title":"Cinderella II: Dreams Come True"},
  "Pongo": { "Voice":"Rod Taylo [21", "Movie Title":"101 Dalmatians"},
  "Powerline": { "Voice":"Tevin Campbell", "Movie Title":"A Goofy Movie"},
  "Practical Pig": { "Voice":"Pinto Colvig", "Movie Title":"Three Little Pigs"},
  "Preston B. Whitmore": { "Voice":"John Mahone [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Pretty Boy": { "Voice":"Jerry Stille [56", "Movie Title":"Teachers Pet"},
  "Prince": { "Voice":"Harry Stockwel [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Prince Charming": { "Voice":"William Phipp [17", "Movie Title":"Cinderella"},
  "Prince Edward": { "Voice":"James Marsden", "Movie Title":"Enchanted"},
  "Prince Eric": { "Voice":"Christopher Daniel Barne [6", "Movie Title":"The Little Mermaid"},
  "Prince Hans": { "Voice":"Santino Fontana", "Movie Title":"Frozen"},
  "Prince James": { "Voice":"Zach Callison", "Movie Title":"Sofia the First"},
  "Prince John": { "Voice":"Peter Ustino [13", "Movie Title":"Robin Hood"},
  "Prince Naveen": { "Voice":"Bruno Campo [42", "Movie Title":"The Princess and the Frog"},
  "Prince Phillip": { "Voice":"Bill Shirle [28", "Movie Title":"Sleeping Beauty"},
  "Princess": { "Voice":"Queenie Leonar [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Princess Amber": { "Voice":"Darcy Rose Byrnes", "Movie Title":"Sofia the First"},
  "Princess Eilonwy": { "Voice":"Susan Sherida [49", "Movie Title":"The Black Cauldron"},
  "Princess Jasmine": { "Voice":"Linda Larkin\nLea Salong [4", "Movie Title":"Aladdin"},
  "Princess Kidagakash": { "Voice":"Cree Summe [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Principal Mazur": { "Voice":"Wallace Shawn", "Movie Title":"A Goofy Movie"},
  "Prissy the Elephant": { "Voice":"Sarah Selb [44", "Movie Title":"Dumbo"},
  "Professor Norton Nimnul": { "Voice":"Jim Cummings", "Movie Title":"Chip n Dale Rescue Rangers"},
  "Professor Ratigan": { "Voice":"Vincent Pric [34", "Movie Title":"The Great Mouse Detective"},
  "Pronk Oryx-Antlerson": { "Voice":"Jared Bush", "Movie Title":"Zootopia"},
  "Prudence": { "Voice":"Holland Taylor", "Movie Title":"Cinderella II: Dreams Come True"},
  "Psycho the Weasel": { "Voice":"Charles Fleische [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Pua": { "Voice":"None", "Movie Title":"Moana"},
  "Pumbaa": { "Voice":"Ernie Sabell [33", "Movie Title":"The Lion King"},
  "Quackerjack": { "Voice":"Michael Bell", "Movie Title":"Darkwing Duck"},
  "Quasimodo": { "Voice":"Tom Hulc [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Queen": { "Voice":"Kari Wahlgren", "Movie Title":"Tangled Ever After"},
  "Queen Athena": { "Voice":"Lorelei Hill Butters", "Movie Title":"The Little Mermaid: Ariels Beginning"},
  "Queen Clarion": { "Voice":"Anjelica Huston", "Movie Title":"Disney Fairies"},
  "Queen Grimhilde": { "Voice":"Lucille La Vern [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Queen Leah": { "Voice":"Barbara Dirikson", "Movie Title":"Sleeping Beauty"},
  "Queen Miranda": { "Voice":"Sara Ramirez", "Movie Title":"Sofia the First"},
  "Queen Mousetoria": { "Voice":"Eve Brenne [34", "Movie Title":"The Great Mouse Detective"},
  "Queen Narissa": { "Voice":"Susan Sarandon", "Movie Title":"Enchanted"},
  "The Queen of Hearts": { "Voice":"Verna Felto [15", "Movie Title":"Alice in Wonderland"},
  "Quint": { "Voice":"Corey Burton", "Movie Title":"Timon and Pumbaa"},
  "Rabbit": { "Voice":"Junius Matthew [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Rachel": { "Voice":"None", "Movie Title":"Fantasia 2000"},
  "Rafiki": { "Voice":"Robert Guillaum [33", "Movie Title":"The Lion King"},
  "Rajah": { "Voice":"Frank Welker", "Movie Title":"Aladdin"},
  "Rancis Fluggerbutter": { "Voice":"Jamie Elman", "Movie Title":"Wreck-It Ralph"},
  "Rapunzel": { "Voice":"Mandy Moor [52", "Movie Title":"Tangled"},
  "Ratty": { "Voice":"Claud Alliste [20", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Ray the Firefly": { "Voice":"Jim Cumming [42", "Movie Title":"The Princess and the Frog"},
  "Razoul": { "Voice":"Jim Cumming [4", "Movie Title":"Aladdin"},
  "Red": { "Voice":"Peter Firt [48", "Movie Title":"The Rescuers Down Under"},
  "Rhino": { "Voice":"Mark Walto [7", "Movie Title":"Bolt"},
  "Rhoda Dendron": { "Voice":"Jennifer Darling", "Movie Title":"Darkwing Duck"},
  "Rico": { "Voice":"Charles Denni [12", "Movie Title":"Home on the Range"},
  "The Ringmaster": { "Voice":"Herman Bin [44", "Movie Title":"Dumbo"},
  "Rita": { "Voice":"Sheryl Lee Ralp [51", "Movie Title":"Oliver & Company"},
  "Robert ": { "Voice":"Pauly Shore", "Movie Title":"A Goofy Movie"},
  "Robin Hood": { "Voice":"Brian Bedfor [13", "Movie Title":"Robin Hood"},
  "Roger Rabbit": { "Voice":"Charles Fleische [30", "Movie Title":"Who Framed Roger Rabbit"},
  "Roger Radcliffe": { "Voice":"Ben Wrigh [21", "Movie Title":"101 Dalmatians"},
  "Rolly": { "Voice":"Barbara Beair [21", "Movie Title":"One Hundred and One Dalmatians"},
  "Ronno": { "Voice":"Anthony Ghannam", "Movie Title":"Bambi II"},
  "Roo": { "Voice":"Clint Howar [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Dori Whittake [47": { "Voice":"", "Movie Title":""},
  "Roquefort the Mouse": { "Voice":"Sterling Hollowa [2", "Movie Title":"The Aristocats"},
  "Roscoe": { "Voice":"Taurean Blacqu [51", "Movie Title":"Oliver & Company"},
  "The Rose": { "Voice":"Doris Lloy [15", "Movie Title":"Alice in Wonderland"},
  "Rosetta": { "Voice":"Kristin Chenoweth", "Movie Title":"Disney Fairies"},
  "Roxanne": { "Voice":"Kellie Martin", "Movie Title":"A Goofy Movie"},
  "Ruby": { "Voice":"Cathy Moriart [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Rufus": { "Voice":"John McIntir [37", "Movie Title":"The Rescuers"},
  "Runt of the Litter": { "Voice":"Steve Zah [1", "Movie Title":"Chicken Little"},
  "Rusty the Dog": { "Voice":"G.W. Baile [12", "Movie Title":"Home on the Range"},
  "Rutt and Tuke": { "Voice":"Rick Morani [50 \nDave Thoma [50", "Movie Title":"Brother Bear"},
  "Saluk": { "Voice":"Jerry Orbac [45", "Movie Title":"Aladdin and the King of Thieves"},
  "Sadira": { "Voice":"Kellie Martin", "Movie Title":"Aladdin (TV series)"},
  "Sam Flynn": { "Voice":"Garrett John Hedlun [12", "Movie Title":"Tron: Legacy"},
  "Sam the Sheriff": { "Voice":"Richard Riehl [12", "Movie Title":"Home on the Range"},
  "Sarabi": { "Voice":"Madge Sinclai [33", "Movie Title":"The Lion King"},
  "Sarafina": { "Voice":"Zoe Leade [33", "Movie Title":"The Lion King"},
  "Sarah Hawkins": { "Voice":"Laurie Metcal [29", "Movie Title":"Treasure Planet"},
  "Sarousch": { "Voice":"Michael McKea [55", "Movie Title":"The Hunchback of Notre Dame II"},
  "Scamp": { "Voice":"Scott Wolf", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Scar": { "Voice":"Jeremy Iron [33", "Movie Title":"The Lion King"},
  "Scat Cat": { "Voice":"Scatman Crother [2", "Movie Title":"The Aristocats"},
  "Scratchy": { "Voice":"None", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Scrooge McDuck": { "Voice":"Alan Young", "Movie Title":"DuckTales"},
  "Scroop": { "Voice":"Michael Wincot [29", "Movie Title":"Treasure Planet"},
  "Scuttle": { "Voice":"Buddy Hacket [6", "Movie Title":"The Little Mermaid"},
  "Sebastian": { "Voice":"Samuel E. Wrigh [6", "Movie Title":"The Little Mermaid"},
  "Secretary Bird": { "Voice":"Lennie Weinrib", "Movie Title":"Bedknobs and Broomsticks"},
  "Sergeant Calhoun": { "Voice":"Jane Lynch", "Movie Title":"Wreck-It Ralph"},
  "Sgt. Tibbs": { "Voice":"David Frankha [21", "Movie Title":"101 Dalmatians"},
  "Shan Yu": { "Voice":"Miguel Ferre [46", "Movie Title":"Mulan"},
  "Shanti (The Girl)": { "Voice":"Darleen Carr", "Movie Title":"The Jungle Book"},
  "Sha-ron": { "Voice":"Mary Gibbs", "Movie Title":"Mulan 2"},
  "Shenzi": { "Voice":"Whoopi Goldber [33", "Movie Title":"The Lion King"},
  "Shere Khan": { "Voice":"George Sander [9", "Movie Title":"The Jungle Book"},
  "Sheriff of Nottingham": { "Voice":"Pat Buttra [13", "Movie Title":"Robin Hood"},
  "Shun Gon the Chinese Cat": { "Voice":"Paul Winchel [2", "Movie Title":"The Aristocats"},
  "Si & Am": { "Voice":"Peggy Le [27", "Movie Title":"Lady and the Tramp"},
  "Silvermist": { "Voice":"Lucy Liu", "Movie Title":"Disney Fairies"},
  "Simba": { "Voice":"Jonathan Taylor Thoma [33", "Movie Title":"The Lion King"},
  "Matthew Broderic [33": { "Voice":"", "Movie Title":""},
  "Sir Ector": { "Voice":"Sebastian Cabo [24", "Movie Title":"The Sword in the Stone"},
  "Sir Giles": { "Voice":"Claud Allister", "Movie Title":"The Reluctant Dragon"},
  "Sir Hiss": { "Voice":"Terry-Thoma [13", "Movie Title":"Robin Hood"},
  "Sir Kay": { "Voice":"Norman Alde [24", "Movie Title":"The Sword in the Stone"},
  "Sir Pellinore": { "Voice":"Alan Napie [24", "Movie Title":"The Sword in the Stone"},
  "Sis Bunny": { "Voice":"Dana Laurit [13", "Movie Title":"Robin Hood"},
  "Sitka": { "Voice":"D. B. Sweene [50", "Movie Title":"Brother Bear"},
  "Skippy Bunny": { "Voice":"Billy Whittake [13", "Movie Title":"Robin Hood"},
  "Sleepy": { "Voice":"Pinto Colvi [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Slightly": { "Voice":"Stuffy Singe [43", "Movie Title":"Peter Pan"},
  "Smarty the Weasel": { "Voice":"David Lander", "Movie Title":"Who Framed Roger Rabbit"},
  "Smolder the Bear": { "Voice":"Jim Cummings", "Movie Title":"Timon and Pumbaa"},
  "Sneezy": { "Voice":"Billy Gilber [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Snow White": { "Voice":"Adriana Caselott [35", "Movie Title":"Snow White and the Seven Dwarfs"},
  "Snowanna Rainbeau": { "Voice":"None", "Movie Title":"Wreck-It Ralph"},
  "Princess Sofia": { "Voice":"Ariel Winter", "Movie Title":"Sofia the First"},
  "Sour Bill": { "Voice":"Rich Moore", "Movie Title":"Wreck-It Ralph"},
  "Sparky": { "Voice":"Mickey Roone [19", "Movie Title":"Lady and the Tramp II: Scamps Adventure"},
  "Speedy the Snail": { "Voice":"Corey Burton", "Movie Title":"Timon and Pumbaa"},
  "Spot": { "Voice":"Tara Strong", "Movie Title":"101 Dalmatians: The Series"},
  "Spot Helperman/Scott Leadready II": { "Voice":"Nathan Lane", "Movie Title":"Teachers Pet"},
  "Spring Sprite": { "Voice":"Helena Bonham Carter", "Movie Title":"Fantasia 2000"},
  "Squeaks the Caterpillar": { "Voice":"None", "Movie Title":"The Fox and the Hound"},
  "Stabbington Brothers": { "Voice":"Ron Perlma [52", "Movie Title":"Tangled"},
  "Steelbeak": { "Voice":"Rob Paulsen", "Movie Title":"Darkwing Duck"},
  "Stitch": { "Voice":"Chris Sander [8", "Movie Title":"Lilo & Stitch"},
  "Stromboli": { "Voice":"Charles Judel [38", "Movie Title":"Pinocchio"},
  "Stu Hopps": { "Voice":"Don Lake", "Movie Title":"Zootopia"},
  "Stupid the Weasel": { "Voice":"Fred Newma [30", "Movie Title":"Who Framed Roger Rabbit"},
  "The Sultan": { "Voice":"Douglas Seal [4", "Movie Title":"Aladdin"},
  "Sultan the Footstool": { "Voice":"Frank Welke [25", "Movie Title":"Beauty and the Beast"},
  "Suri": { "Voice":"Hayden Panettier [11", "Movie Title":"Dinosaur"},
  "Sven": { "Voice":"None", "Movie Title":"Frozen"},
  "Swizzle ": { "Voice":"None", "Movie Title":"Wreck-It Ralph"},
  "Sykes": { "Voice":"Robert Loggi [51", "Movie Title":"Oliver & Company"},
  "Sylvia Marpole": { "Voice":"Bebe Neuwirth", "Movie Title":"An Extremely Goofy Movie"},
  "Tadashi Hamada": { "Voice":"Daniel Henney", "Movie Title":"Big Hero 6"},
  "Taffyta Muttonfudge": { "Voice":"Mindy Kaling", "Movie Title":"Wreck-It Ralph"},
  "Tagalong Bunny": { "Voice":"Dori Whittake [13", "Movie Title":"Robin Hood"},
  "Tamatoa": { "Voice":"Jemaine Clement", "Movie Title":"Moana"},
  "Tanana": { "Voice":"Joan Copelan [50", "Movie Title":"Brother Bear"},
  "Tank": { "Voice":"Brad Garrett", "Movie Title":"An Extremely Goofy Movie"},
  "Tank Muddlefoot": { "Voice":"Dana Hill", "Movie Title":"Darkwing Duck"},
  "Tantor": { "Voice":"Wayne Knigh [23", "Movie Title":"Tarzan"},
  "Tantors Mother": { "Voice":"Patti Deutsc [23", "Movie Title":"Tarzan"},
  "Taran": { "Voice":"Grant Bardsle [49", "Movie Title":"The Black Cauldron"},
  "Tarzan": { "Voice":"Tony Goldwy [23", "Movie Title":"Tarzan"},
  "Alex D. Lin [23": { "Voice":"", "Movie Title":""},
  "Taurus Bulba": { "Voice":"Tim Curry", "Movie Title":"Darkwing Duck"},
  "Ted Betterhead": { "Voice":"Diedrich Bader", "Movie Title":"The Country Bears"},
  "Terence": { "Voice":"Jesse McCartney", "Movie Title":"Disney Fairies"},
  "Terk": { "Voice":"Rosie ODonnel [23", "Movie Title":"Tarzan"},
  "Terpsichore": { "Voice":"LaChanz [14", "Movie Title":"Hercules"},
  "Thalia": { "Voice":"Roz Rya [14", "Movie Title":"Hercules"},
  "Thomas": { "Voice":"Christian Bal [36", "Movie Title":"Pocahontas"},
  "Thomas OMalley": { "Voice":"Phil Harri [2", "Movie Title":"The Aristocats"},
  "Thug": { "Voice":"Randy Savag [7", "Movie Title":"Bolt"},
  "Thumper": { "Voice":"Peter Beh [32 \nSam Edward [32", "Movie Title":"Bambi"},
  "Thumpers Mother": { "Voice":"Margaret Le [32", "Movie Title":"Bambi"},
  "Tiana": { "Voice":"Anika Noni Ros [42", "Movie Title":"The Princess and the Frog"},
  "Tiger Lily": { "Voice":"Cree Summer", "Movie Title":"Peter Pan"},
  "Tigger": { "Voice":"Paul Winchel [47", "Movie Title":"Winnie the Pooh and the Blustery Day"},
  "Tillie Tiger": { "Voice":"Alyce Ardel [53", "Movie Title":"Silly Symphonies"},
  "Timon": { "Voice":"Nathan Lan [33", "Movie Title":"The Lion King"},
  "Timons Mother": { "Voice":"Julie Kavner", "Movie Title":"The Lion King 1½"},
  "Timothy Q. Mouse": { "Voice":"Edward Broph [44", "Movie Title":"Dumbo"},
  "Tina": { "Voice":"Catherine OHar [1", "Movie Title":"Chicken Little"},
  "Tinker Bell": { "Voice":"Mae Whitman", "Movie Title":"Peter Pan"},
  "Tino Tonitini": { "Voice":"Jason Marsden", "Movie Title":"The Weekenders"},
  "Tiny": { "Voice":"Joe Mate [39", "Movie Title":"Meet the Robinsons"},
  "Tip": { "Voice":"Max Casella", "Movie Title":"The Little Mermaid II: Return to the Sea"},
  "Tipo": { "Voice":"Eli Russell Linnet [41", "Movie Title":"The Emperors New Groove"},
  "Tito": { "Voice":"Cheech Mari [51", "Movie Title":"Oliver & Company"},
  "Tobias the Reluctant Dragon": { "Voice":"Barnett Parke [60", "Movie Title":"The Reluctant Dragon"},
  "Toby the Dog": { "Voice":"Frank Welke [34", "Movie Title":"The Great Mouse Detective"},
  "Toby Tortoise": { "Voice":"Eddie Holde [58", "Movie Title":"The Tortoise and the Hare"},
  "Toby Turtle": { "Voice":"Richie Sanders", "Movie Title":"Robin Hood"},
  "Tod": { "Voice":"Keith Cooga [16 \nMickey Roone [16", "Movie Title":"The Fox and the Hound"},
  "Tootles": { "Voice":"None", "Movie Title":"Peter Pan"},
  "Toots": { "Voice":"Frank Welker", "Movie Title":"Bonkers"},
  "Toulouse": { "Voice":"Gary Dubi [2", "Movie Title":"The Aristocats"},
  "Tramp": { "Voice":"Larry Robert [27", "Movie Title":"Lady and the Tramp"},
  "Trigger the Vulture": { "Voice":"George Lindse [13", "Movie Title":"Robin Hood"},
  "Trusty": { "Voice":"Bill Bauco [27", "Movie Title":"Lady and the Tramp"},
  "Tug": { "Voice":"Michael Clarke Dunca [50", "Movie Title":"Brother Bear"},
  "Tui": { "Voice":"Temuera Morrison", "Movie Title":"Moana"},
  "Turkey Lurkey": { "Voice":"Don Knott [1", "Movie Title":"Chicken Little"},
  "Tuskernini": { "Voice":"Kenneth Mars", "Movie Title":"Darkwing Duck"},
  "Tweedledum and Tweedledee": { "Voice":"J. Pat OMalle [15", "Movie Title":"Alice in Wonderland"},
  "Two Fingers": { "Voice":"Paul Brigg [42", "Movie Title":"The Princess and the Frog"},
  "Uncle Art": { "Voice":"Adam Wes [39", "Movie Title":"Meet the Robinsons"},
  "Uncle Max": { "Voice":"Jerry Stiller", "Movie Title":"The Lion King 1½"},
  "Uncle Waldo": { "Voice":"Bill Thompso [2", "Movie Title":"The Aristocats"},
  "Url": { "Voice":"None", "Movie Title":"Dinosaur"},
  "Ursula": { "Voice":"Pat Carrol [6", "Movie Title":"The Little Mermaid"},
  "Vanellope von Schweetz": { "Voice":"Sarah Silverman", "Movie Title":"Wreck-It Ralph"},
  "Vanessa (The Little Mermaid)": { "Voice":"Pat Carroll [6 Jodi Benson", "Movie Title":"The Little Mermaid"},
  "Veteran Cat": { "Voice":"Diedrich Bade [7", "Movie Title":"Bolt"},
  "Victor": { "Voice":"Charles Kimbroug [5", "Movie Title":"The Hunchback of Notre Dame"},
  "Vidia": { "Voice":"Pamela Adlon", "Movie Title":"Disney Fairies"},
  "Vincenzo ": { "Voice":"Don Novell [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Vitani": { "Voice":"Lacey Chabert\nJennifer Lien", "Movie Title":"The Lion King II: Simbas Pride"},
  "Vixey": { "Voice":"Sandy Dunca [16", "Movie Title":"The Fox and the Hound"},
  "Vladimir Goudenov Grizzlikof": { "Voice":"Ron Feinberg", "Movie Title":"Darkwing Duck"},
  "Vulture Police": { "Voice":"Townsend Coleman\nBrian Cummings", "Movie Title":"Timon and Pumbaa"},
  "Waffles": { "Voice":"Frank Welker", "Movie Title":"Goof Troop"},
  "The Walrus": { "Voice":"J. Pat OMalle [15", "Movie Title":"Alice in Wonderland"},
  "Webby Vanderquack": { "Voice":"Russi Taylor", "Movie Title":"DuckTales"},
  "Webster": { "Voice":"Jim Cummings", "Movie Title":"Belles Magical World"},
  "Wendy Darling": { "Voice":"Kathryn Beaumon [43", "Movie Title":"Peter Pan"},
  "Wesley": { "Voice":"Steve Buscem [12", "Movie Title":"Home on the Range"},
  "Wheezy the Weasel": { "Voice":"June Fora [30", "Movie Title":"Who Framed Roger Rabbit"},
  "White Rabbit": { "Voice":"Bill Thompso [15", "Movie Title":"Alice in Wonderland"},
  "Widow Tweed": { "Voice":"Jeanette Nola [16", "Movie Title":"The Fox and the Hound"},
  "Wiggins": { "Voice":"David Ogden Stier [36", "Movie Title":"Pocahontas"},
  "Wilbur": { "Voice":"John Cand [48", "Movie Title":"The Rescuers Down Under"},
  "Wilbur Robinson": { "Voice":"Wesley Singerma [39", "Movie Title":"Meet the Robinsons"},
  "Wilhelmina Packard": { "Voice":"Florence Stanle [26", "Movie Title":"Atlantis: The Lost Empire"},
  "Willie the Giant": { "Voice":"Billy Gilber [61", "Movie Title":"Fun and Fancy Free"},
  "Winifred the Elephant": { "Voice":"Verna Felto [9", "Movie Title":"The Jungle Book"},
  "Winkie the Barman": { "Voice":"Oliver Wallac [20", "Movie Title":"The Adventures of Ichabod and Mr. Toad"},
  "Winnie the Pooh": { "Voice":"Sterling Hollowa [47", "Movie Title":"Winnie the Pooh and the Honey Tree"},
  "Winston": { "Voice":"William Glove [51", "Movie Title":"Oliver & Company"},
  "Witherspoon": { "Voice":"None", "Movie Title":"Belles Magical World"},
  "Woolter the Ram": { "Voice":"John DiMaggio", "Movie Title":"Zootopia"},
  "Wormwood the Raven": { "Voice":"Jim Cummings", "Movie Title":"Sofia the First"},
  "Wreck-It Ralph": { "Voice":"John C. Reilly", "Movie Title":"Wreck-It Ralph"},
  "Wynchel": { "Voice":"Adam Carolla", "Movie Title":"Wreck-It Ralph"},
  "Xerxes": { "Voice":"Frank Welker", "Movie Title":"Aladdin (TV series)"},
  "Yao": { "Voice":"Harvey Fierstei [46", "Movie Title":"Mulan"},
  "Yar": { "Voice":"Ossie Davi [11", "Movie Title":"Dinosaur"},
  "Yax": { "Voice":"Tommy Chong", "Movie Title":"Zootopia"},
  "Yen Sid": { "Voice":"Corey Burton", "Movie Title":"Fantasia"},
  "Yo-Yo": { "Voice":"None", "Movie Title":"Fantasia 2000"},
  "Yzma": { "Voice":"Eartha Kit [41", "Movie Title":"The Emperors New Groove"},
  "Zeus": { "Voice":"Rip Tor [14", "Movie Title":"Hercules"},
  "Ziggy the Vulture": { "Voice":"Digby Wolf [9", "Movie Title":"The Jungle Book"},
  "Zini": { "Voice":"Max Casell [11", "Movie Title":"Dinosaur"},
  "Zipper": { "Voice":"Corey Burton", "Movie Title":"Chip n Dale Rescue Rangers"},
  "Zira": { "Voice":"Suzanne Pleshette", "Movie Title":"The Lion King II: Simbas Pride"}
}
